Constraints (future and past) for Date and LocalDate
domain-primitives/domain-primitives-java pull request #5
Opened 2022-01-28 11:57 UTC by lwluc

2022-01-28 12:45 UTC, slu-it approved these changes

2022-01-31 11:15 UTC, Drakojin commented on src/main/java/de/novatec/ddd/domainprimitives/validation/Constraints.java
> +    public static Consumer<Validation<LocalDate>> isInFutureLocalDate() {
I would suggest to base this on the "Temporal" Interface and check based on implementation to offer wider support of java.time

2022-01-31 11:15 UTC, Drakojin commented on src/main/java/de/novatec/ddd/domainprimitives/validation/Constraints.java
> +        return val -> val.constraint(
Most of Date is deprecated. Maybe forward the check to Temporal?

2022-02-01 12:39 UTC, Drakojin requested changes

2022-02-01 12:39 UTC, Drakojin commented on src/test/java/de/novatec/ddd/domainprimitives/validation/ConstraintsTest.java
> +                Temporal future = of(now().getYear() + 1, now().getMonth(), now().getDayOfMonth());
Add ParameterizedTest for every supported type and for UnsupportedException

2022-02-02 07:04 UTC, Drakojin approved these changes

2022-02-04 13:54 UTC, merged